In [13]:
import numpy as np

def pp(obj):
    print(repr(obj))

In [18]:
a = [1, 2, 3]
b = [4, 5, 6]
pp(a)

c = np.array([1, 2, 3])
d = np.array([4, 5, 6])
pp(c)

pp([q * 2 for q in a])
pp(c * 2)

pp([q + r for q, r in zip(a, b)])
pp(c + d)

[1, 2, 3]
array([1, 2, 3])
[2, 4, 6]
array([2, 4, 6])
[5, 7, 9]
array([5, 7, 9])
